### PR TITLE
Clean up code of repeat, and add working repeat, and remove mentions to it not working, and the all-usable and all-unusable is now just all

### PR DESCRIPTION
**Pull request by Toxidation2**

### CODE REVIEW

**Comment by Toxidation2** [comment]
There. Enjoy!

**Review by thenxguy — CHANGES_REQUESTED** [review]
This does not function as intended.

Intended: repeat a b c
a b c a b c a b c a b c a b c a b c a b c ...
Actual: repeat a b c
c c c c c c c c c c c c c c c

**Review by thenxguy — CHANGES_REQUESTED** [review]
The makefile has bad formatting and does not work.
Remove the whitespace after "all:"

**Comment by Toxidation2** [comment]
Ah OK. I'll look in to it.

**Comment by Toxidation2** [comment]
Yeah, I think it's somehow overwriting the variable, if that makes any sense.

Also, I'll try to update the Makefile

**Comment by Toxidation2** [comment]
Fixed.

**Review by thenxguy — APPROVED** [review]
All good.

**Pull request merged**
